#!/bin/bash

#https://repo2docker.readthedocs.io/en/latest/configuration/actions/#postbuild-run-code-after-installing-the-environment
set -e

# for binder we run as uid=1000 so change the owner of directory
chown 1000:1000 -R /home/$MAMBA_USER
